apiVersion: v1
kind: Endpoints
metadata:
  name: rass
  namespace: default
subsets:
  - addresses:
    # list all external ips for this service
      - ip: 192.168.102.44
    ports:
      - name: default
        port: 8123
        protocol: TCP