apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    hajimari.io/enable: "true"
    hajimari.io/icon: console
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-secured-chain@kubernetescrd
  name: home
  namespace: external
spec:
  ingressClassName: traefik
  rules:
    - host: "${SECRET_HOME_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: home
                port:
                  number: 8123
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "${SECRET_HOME_DOMAIN}"
      secretName: home-tls