---
apiVersion: v1
kind: Service
metadata:
  name: unraid
  namespace: default
spec:
  ports:
    - name: tristian
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: gitlab
      port: 9080
      protocol: TCP
      targetPort: 9080
    - name: nextcloud
      port: 443
      protocol: TCP
      targetPort: 444
    - name: kutt
      port: 3001
      protocol: TCP
      targetPort: 3001
    - name: default
      port: 81
      protocol: TCP
      targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unraid
  namespace: default
subsets:
  - addresses:
    # list all external ips for this service
      - ip: 192.168.102.46
    ports:
      - name: tristian
        port: 3000
        protocol: TCP
      - name: gitlab
        port: 9080
        protocol: TCP
      - name: nextcloud
        port: 444
        protocol: TCP
      - name: kutt
        port: 3001
        protocol: TCP
      - name: default
        port: 80
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    hajimari.io/enable: "true"
    hajimari.io/icon: console
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-secured-chain@kubernetescrd
  name: unraid
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: "${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: kutt
                port:
                  number: 3001
            path: /x
            pathType: Exact
    - host: "${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: unraid
                port:
                  number: 3000
            path: /
            pathType: Prefix
    - host: "git.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: unraid
                port:
                  number: 9080
            path: /
            pathType: Prefix
    - host: "cloud.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: unraid
                port:
                  number: 443
            path: /
            pathType: Prefix
    - host: "ur.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: unraid
                port:
                  number: 81
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "${SECRET_DOMAIN}"
        - "git.${SECRET_DOMAIN}"
        - "cloud.${SECRET_DOMAIN}"
        - "ur.${SECRET_DOMAIN}"
      secretName: tristian-tls
status:
  loadBalancer:
    ingress:
      - ip: 192.168.102.46
