apiVersion: v1
kind: Endpoints
metadata:
  name: hosting
  namespace: default
subsets:
  - addresses:
    # list all external ips for this service
      - ip: 192.168.102.84
    ports:
      - name: default
        port: 443
        protocol: TCP