---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-gitops
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/appName: "weave"
    hajimari.io/enable: "true"
    hajimari.io/icon: "source-branch-sync"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "default-secured-chain@kubernetescrd"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "${SECRET_WEAVE_DOMAIN}"
      secretName: "weave-gitops-tls"
  rules:
    - host: "${SECRET_WEAVE_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weave-gitops
                port:
                  number: 9001
