apiVersion: v1
kind: Endpoints
metadata:
  name: storage
  namespace: external
subsets:
  - addresses:
      - ip: 192.168.102.46
    ports:
      - name: default
        port: 80
        protocol: TCP
        