apiVersion: v1
kind: Service
metadata:
  name: nodepi0
  namespace: external
spec:
  ports:
    - name: default
      port: 1880
      protocol: TCP
      targetPort: 1880
  clusterIP: None
  type: ClusterIP
