apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - camx
  - cam0
  - cam1
  - cam2
  - cam3
  - frontback
  - livingsensor
  - kitchensensor
  - mybed
  - anyabed
  - power
  - backside
  - nodepi
  - nodepi0
  - watermeter
  - watersupply
  - dining
  - bath
  - rf
  - mining
  - front
